### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _mysql_init

### ISSUE THREAD

**Issue by flaviodelgrosso** [perl5-dbi/DBD-mysql#325]
I'm encountering a message seen for the first time when I execute a perl script requiring DBD::mysql module.

I'm working on macOS 11.1 on ARM64, my perl version is 5.26.3 installed with perlbrew ( I tried also with 5.30.3 and 5.32.0).

The message is:

    dyld: lazy symbol binding failed: Symbol not found: _mysql_init
      Referenced from: /Users/test/perl5/perlbrew/perls/perl-5.26.3/lib/site_perl/5.26.3/darwin-2level/auto/DBD/mysql/mysql.bundle
      Expected in: flat namespace
    
    dyld: Symbol not found: _mysql_init
      Referenced from: /Users/test/perl5/perlbrew/perls/perl-5.26.3/lib/site_perl/5.26.3/darwin-2level/auto/DBD/mysql/mysql.bundle
      Expected in: flat namespace
    
    Abort trap: 6

In my `.bash_profile` and `.bashrc` I've added these lines:

    export PATH="/usr/local/mysql/bin:${PATH}"
    export DYLD_LIBRARY_PATH="/usr/local/mysql/lib:${DYLD_LIBRARY_PATH}"

Any idea how this can be fixed?

EDIT:

When I try to run `make`, I get these warnings:

`ld: warning: ignoring file /usr/local/mysql/lib/libssl.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64 
ld: warning: ignoring file /usr/local/mysql/lib/libcrypto.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64 
ld: warning: ignoring file /usr/local/mysql/lib/libmysqlclient.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64`

Can these be ignored?

Thanks in advance

**Comment by hakonhagland** [comment]
Can you run add the complete output of running:
```
$ make clean
$ perl Makefile.PL
$ make
```

**Comment by flaviodelgrosso** [comment]
> Can you run add the complete output of running:
> 
> ```
> $ make realclean
> $ perl Makefile.PL
> $ make
> ```

Hi Håkon! My make realclean output is: `make: *** No rule to make target 'realclean'.  Stop.` How can fix that?

perl Makefile.PL output is:

```
PLEASE NOTE:

For 'make test' to run properly, you must ensure that the
database user 'flaviodelgrosso' can connect to your MySQL server
and has the proper privileges that these tests require such
as 'drop table', 'create table', 'drop procedure', 'create procedure'
as well as others.

mysql> grant all privileges on test.* to 'flaviodelgrosso'@'localhost' identified by 's3kr1t';

You can also optionally set the user to run 'make test' with:

perl Makefile.PL --testuser=username

I will use the following settings for compiling and testing:

  cflags        (mysql_config) = -I/usr/local/mysql/include
  embedded      (guessed     ) = 
  ldflags       (guessed     ) = 
  libs          (mysql_config) = -L/usr/local/mysql/lib -lmysqlclient -lssl -lcrypto -lresolv
  mysql_config  (guessed     ) = mysql_config
  nocatchstderr (default     ) = 0
  nofoundrows   (default     ) = 0
  nossl         (default     ) = 0
  testdb        (default     ) = test
  testhost      (default     ) = 
  testpassword  (default     ) = 
  testport      (default     ) = 
  testsocket    (default     ) = 
  testuser      (guessed     ) = flaviodelgrosso

To change these settings, see 'perl Makefile.PL --help' and
'perldoc DBD::mysql::INSTALL'.

Checking if libs are available for compiling...
Looks good.

Checking if your kit is complete...
Looks good
Using DBI 1.643 (for perl 5.026003 on darwin-2level) installed in /Users/flaviodelgrosso/perl5/perlbrew/perls/perl-5.26.3/lib/site_perl/5.26.3/darwin-2level/auto/DBI/
Generating a Unix-style Makefile
Writing Makefile for DBD::mysql
Writing MYMETA.yml and MYMETA.json
```

And this the output of `make`:

```
cp lib/DBD/mysql/GetInfo.pm blib/lib/DBD/mysql/GetInfo.pm
cp lib/DBD/mysql/INSTALL.pod blib/lib/DBD/mysql/INSTALL.pod
cp lib/Bundle/DBD/mysql.pm blib/lib/Bundle/DBD/mysql.pm
cp lib/DBD/mysql.pm blib/lib/DBD/mysql.pm
Running Mkbootstrap for mysql ()
chmod 644 "mysql.bs"
"/Users/flaviodelgrosso/perl5/perlbrew/perls/perl-5.26.3/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- mysql.bs blib/arch/auto/DBD/mysql/mysql.bs 644
cc -c  -I/Users/flaviodelgrosso/perl5/perlbrew/perls/perl-5.26.3/lib/site_perl/5.26.3/darwin-2level/auto/DBI -I/usr/local/mysql/include -DDBD_MYSQL_WITH_SSL -g  -fno-common -DPERL_DARWIN -mmacosx-version-min=11.1 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV -O3   -DVERSION=\"4.050\" -DXS_VERSION=\"4.050\"  "-I/Users/flaviodelgrosso/perl5/perlbrew/perls/perl-5.26.3/lib/5.26.3/darwin-2level/CORE"   dbdimp.c
"/Users/flaviodelgrosso/perl5/perlbrew/perls/perl-5.26.3/bin/perl" -p -e "s/~DRIVER~/mysql/g" /Users/flaviodelgrosso/perl5/perlbrew/perls/perl-5.26.3/lib/site_perl/5.26.3/darwin-2level/auto/DBI/Driver.xst > mysql.xsi
"/Users/flaviodelgrosso/perl5/perlbrew/perls/perl-5.26.3/bin/perl" "/Users/flaviodelgrosso/perl5/perlbrew/perls/perl-5.26.3/lib/5.26.3/ExtUtils/xsubpp"  -typemap '/Users/flaviodelgrosso/perl5/perlbrew/perls/perl-5.26.3/lib/5.26.3/ExtUtils/typemap'  mysql.xs > mysql.xsc
Warning: duplicate function definition 'do' detected in mysql.xs, line 247
Warning: duplicate function definition 'rows' detected in mysql.xs, line 683
mv mysql.xsc mysql.c
cc -c  -I/Users/flaviodelgrosso/perl5/perlbrew/perls/perl-5.26.3/lib/site_perl/5.26.3/darwin-2level/auto/DBI -I/usr/local/mysql/include -DDBD_MYSQL_WITH_SSL -g  -fno-common -DPERL_DARWIN -mmacosx-version-min=11.1 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV -O3   -DVERSION=\"4.050\" -DXS_VERSION=\"4.050\"  "-I/Users/flaviodelgrosso/perl5/perlbrew/perls/perl-5.26.3/lib/5.26.3/darwin-2level/CORE"   mysql.c
cc -c  -I/Users/flaviodelgrosso/perl5/perlbrew/perls/perl-5.26.3/lib/site_perl/5.26.3/darwin-2level/auto/DBI -I/usr/local/mysql/include -DDBD_MYSQL_WITH_SSL -g  -fno-common -DPERL_DARWIN -mmacosx-version-min=11.1 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV -O3   -DVERSION=\"4.050\" -DXS_VERSION=\"4.050\"  "-I/Users/flaviodelgrosso/perl5/perlbrew/perls/perl-5.26.3/lib/5.26.3/darwin-2level/CORE"   socket.c
rm -f blib/arch/auto/DBD/mysql/mysql.bundle
LD_RUN_PATH="/usr/local/mysql/lib:/usr/lib" cc  -mmacosx-version-min=11.1 -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector-strong dbdimp.o mysql.o socket.o  -o blib/arch/auto/DBD/mysql/mysql.bundle  \
	   -L/usr/local/mysql/lib -lmysqlclient -lssl -lcrypto -lresolv   \
	  
ld: warning: ignoring file /usr/local/mysql/lib/libssl.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/mysql/lib/libmysqlclient.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/mysql/lib/libcrypto.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
chmod 755 blib/arch/auto/DBD/mysql/mysql.bundle
Manifying 3 pod documents
```
