### ISSUE TITLE
build failure with mariadb-11.4.7

### ISSUE THREAD

**Issue by 0-wiz-0** [perl5-dbi/DBD-mysql#481]
### DBD::mysql version

5.013

### MySQL client version

11.4.7

### Server version

n/a

### Operating system version

NetBSD, but probably irrelevant

### What happened?

In the process of updating the package to the latest version, I see a new build failure:
```
dbdimp.c: In function 'parse_params':
dbdimp.c:639:22: warning: implicit declaration of function 'mysql_real_escape_string_quote'; did you mean 'mysql_real_escape_string'? [-Wimplicit-function-declaration]
  639 |               ptr += mysql_real_escape_string_quote(sock, ptr, valbuf, vallen, '\'');
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      mysql_real_escape_string
dbdimp.c: In function 'mysql_dr_connect':
dbdimp.c:1244:31: error: 'MYSQL_OPT_COMPRESSION_ALGORITHMS' undeclared (first use in this function)
 1244 |           mysql_options(sock, MYSQL_OPT_COMPRESSION_ALGORITHMS, calg);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dbdimp.c:1244:31: note: each undeclared identifier is reported only once for each function it appears in
dbdimp.c:1415:31: error: 'MYSQL_OPT_GET_SERVER_PUBLIC_KEY' undeclared (first use in this function); did you mean 'MYSQL_SERVER_PUBLIC_KEY'?
 1415 |           mysql_options(sock, MYSQL_OPT_GET_SERVER_PUBLIC_KEY, &server_get_pubkey);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                               MYSQL_SERVER_PUBLIC_KEY
dbdimp.c:1479:22: error: 'SSL_MODE_PREFERRED' undeclared (first use in this function)
 1479 |           ssl_mode = SSL_MODE_PREFERRED;
      |                      ^~~~~~~~~~~~~~~~~~
dbdimp.c:1481:26: error: 'SSL_MODE_VERIFY_IDENTITY' undeclared (first use in this function)
 1481 |               ssl_mode = SSL_MODE_VERIFY_IDENTITY;
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~
dbdimp.c:1483:26: error: 'SSL_MODE_VERIFY_CA' undeclared (first use in this function)
 1483 |               ssl_mode = SSL_MODE_VERIFY_CA;
      |                          ^~~~~~~~~~~~~~~~~~
dbdimp.c:1485:26: error: 'SSL_MODE_REQUIRED' undeclared (first use in this function)
 1485 |               ssl_mode = SSL_MODE_REQUIRED;
      |                          ^~~~~~~~~~~~~~~~~
dbdimp.c:1486:37: error: 'MYSQL_OPT_SSL_MODE' undeclared (first use in this function); did you mean 'MYSQL_OPT_SSL_CRL'?
 1486 |             if (mysql_options(sock, MYSQL_OPT_SSL_MODE, &ssl_mode) != 0) {
      |                                     ^~~~~~~~~~~~~~~~~~
      |                                     MYSQL_OPT_SSL_CRL
dbdimp.c:1495:37: error: 'SSL_MODE_DISABLED' undeclared (first use in this function)
 1495 |             unsigned int ssl_mode = SSL_MODE_DISABLED;
      |                                     ^~~~~~~~~~~~~~~~~
dbdimp.c: In function 'mysql_st_prepare':
dbdimp.c:2419:24: warning: assignment to 'my_bool *' {aka 'char *'} from incompatible pointer type '_Bool *' [-Wincompatible-pointer-types]
 2419 |           bind->is_null=      &(fbind->is_null);
      |                        ^
dbdimp.c: In function 'mysql_st_internal_execute41':
dbdimp.c:2856:9: warning: implicit declaration of function 'mysql_stmt_bind_named_param'; did you mean 'mysql_stmt_bind_param'? [-Wimplicit-function-declaration]
 2856 |     if (mysql_stmt_bind_named_param(stmt,bind,num_params, NULL))
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         mysql_stmt_bind_param
dbdimp.c: In function 'mysql_describe':
dbdimp.c:3170:22: warning: assignment to 'my_bool *' {aka 'char *'} from incompatible pointer type '_Bool *' [-Wincompatible-pointer-types]
 3170 |       buffer->is_null= &(fbh->is_null);
      |                      ^
dbdimp.c:3171:20: warning: assignment to 'my_bool *' {aka 'char *'} from incompatible pointer type '_Bool *' [-Wincompatible-pointer-types]
 3171 |       buffer->error= (bool*) &(fbh->error);
      |                    ^
```

**Comment by 0-wiz-0** [comment]
In case it matters, previous pkgsrc was was 4.050.

**Comment by dveeden** [comment]
DBD::mysql needs MySQL client libraries and doesn't work with MariaDB client libraries. The old v4 branch has MariaDB compatibility.

Best to build with MySQL 8.4 (or 8.0) libraries or consider switching to DBD:: MariaDB

**Comment by dveeden** [comment]
Side note: as far as I know everything should work fine on NetBSD.
