### PR TITLE
Fix compiling against MariaDB

### LINKED ISSUE #262: token ""mariadb-10.1"" is not valid in preprocessor expressions
Compiling DBD-mysql-4.047 fails on debian/stretch systems:
```
cc -c  -I/opt/perl-5.24.3/lib/site_perl/5.24.3/x86_64-linux/auto/DBI -I/usr/include/mysql -DDBD_MYSQL_WITH_SSL -g  -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2   -DVERSION=\"4.047\" -DXS_VERSION=\"4.047\" -fPIC "-I/opt/perl-5.24.3/lib/5.24.3/x86_64-linux/CORE"   dbdimp.c
In file included from /usr/include/mysql/mysql.h:76:0,
                 from dbdimp.h:21,
                 from dbdimp.c:15:
dbdimp.c: In function 'mysql_dr_connect':
/usr/include/mysql/mysql_version.h:16:31: error: token ""mariadb-10.1"" is not valid in preprocessor expressions
 #define MARIADB_BASE_VERSION  "mariadb-10.1"
                               ^
dbdimp.c:1910:56: note: in expansion of macro 'MARIADB_BASE_VERSION'
 #if (MYSQL_VERSION_ID >= 50723) && (MYSQL_VERSION_ID < MARIADB_BASE_VERSION)
                                                        ^~~~~~~~~~~~~~~~~~~~
/usr/include/mysql/mysql_version.h:16:31: error: token ""mariadb-10.1"" is not valid in preprocessor expressions
 #define MARIADB_BASE_VERSION  "mariadb-10.1"
                               ^
dbdimp.c:1917:56: note: in expansion of macro 'MARIADB_BASE_VERSION'
 #if (MYSQL_VERSION_ID >= 50600) && (MYSQL_VERSION_ID < MARIADB_BASE_VERSION)
                                                        ^~~~~~~~~~~~~~~~~~~~
dbdimp.c: In function 'mysql_st_prepare':
dbdimp.c:3200:24: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
           bind->is_null=      (_Bool*) &(fbind->is_null);
                        ^
Makefile:355: recipe for target 'dbdimp.o' failed
make: *** [dbdimp.o] Error 1
```
DBD-mysql-4.046 compiled fine on this system.

### PR DESCRIPTION
**Pull request by dveeden**
This regression was introduced in #257
Fixes #262

Source: https://bugs.freebsd.org/bugzilla/attachment.cgi?id=196990&action=diff#files/patch-dbdimp.c_sec1

### CODE REVIEW

**Comment by pali** [comment]
This is really nice fix -- equivalent of removing code...
